### ISSUE TITLE
Mapping PS2 Dell keyboard

### ISSUE THREAD

**Issue by arifzeeshan** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#1]
Thank you for maintaining this. 

I have a similar laptop E7470 model. I read your SSDT files and you have patches for Fn keys, Sleep and LID.  Both the laptops have the same keyoard layouts. I tried using your SSDTs but when activating Fn+Insert hotkey, it goes to sleep but when I wake up, it takes so much time with blackscreen and the Brightness keys stop working. I need to reboot to fix it. 

Are you facing similar issues ?

**Comment by Lovely-XPP** [comment]
Thank you for your issues, I don't pay attention to this before. When I try Fn+Insert hotkey, it really doesn't work. I will try to fix it. If fixed, I will update it.

**Comment by Lovely-XPP** [comment]
I updated the EFI just now with this problem solved. Here is the description:
This commit fixes the key 'fn + insert' to sleep. When you active fn + insert, the computer will get into sleep but wake after a while and then it continue to sleep when the screen going black. If you can not wake the laptop by activating any key, you can try to active 'fn + insert' key again, it always work. 
I test it on my macOS 12 beta 5(21A5304g), it works well so far. Don't forget to run this command in the kernel to set proper sleep mode:
`sudo pmset -a hibernatemode 3`
I hope it can be helpful for you.

**Comment by Lovely-XPP** [comment]
> Thank you for maintaining this.
> 
> I have a similar laptop E7470 model. I read your SSDT files and you have patches for Fn keys, Sleep and LID. Both the laptops have the same keyoard layouts. I tried using your SSDTs but when activating Fn+Insert hotkey, it goes to sleep but when I wake up, it takes so much time with blackscreen and the Brightness keys stop working. I need to reboot to fix it.
> 
> Are you facing similar issues ?


I updated the EFI just now with this problem solved. Here is the description:
This commit fixes the key 'fn + insert' to sleep. When you active fn + insert, the computer will get into sleep but wake after a while and then it continue to sleep when the screen going black. If you can not wake the laptop by activating any key, you can try to active 'fn + insert' key again, it always work.
I test it on my macOS 12 beta 5(21A5304g), it works well so far. Don't forget to run this command in the kernel to set proper sleep mode:
sudo pmset -a hibernatemode 3
I hope it can be helpful for you.

**Comment by Lovely-XPP** [comment]
> Thank you for maintaining this.
> 
> I have a similar laptop E7470 model. I read your SSDT files and you have patches for Fn keys, Sleep and LID. Both the laptops have the same keyoard layouts. I tried using your SSDTs but when activating Fn+Insert hotkey, it goes to sleep but when I wake up, it takes so much time with blackscreen and the Brightness keys stop working. I need to reboot to fix it.
> 
> Are you facing similar issues ?


I updated the EFI just now with this problem solved. Here is the description:
This commit fixes the key 'fn + insert' to sleep. When you active fn + insert, the computer will get into sleep but wake after a while and then it continue to sleep when the screen going black. If you can not wake the laptop by activating any key, you can try to active 'fn + insert' key again, it always work.
I test it on my macOS 12 beta 5(21A5304g), it works well so far. Don't forget to run this command in the kernel to set proper sleep mode:

`sudo pmset -a hibernatemode 3`

I hope it can be helpful for you.

**Comment by arifzeeshan** [comment]
Is hibernate working for you ? I have the Hibernatefixup kext.

This is my pmset -g 

```
System-wide power settings:
Currently in use:
 standbydelaylow      10800
 standby              1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 powernap             0
 gpuswitch            2
 disksleep            10
 standbydelayhigh     86400
 sleep                1
 autopoweroffdelay    259200
 hibernatemode        3
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         2
 tcpkeepalive         1
 highstandbythreshold 50
 lidwake              1
```

**Comment by Lovely-XPP** [comment]
Yes, I find the sleep is still working bad. I am working on it these days. The first things I fix is the Gpu, and now I make it. It support HEVC decoding now.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/66028151/130376215-1b615faf-4ee2-4640-a488-1a2c279e906a.png">

Now it can successfully sleep but not in actually sleep, when the screen off, it is still working and consume power. I am trying to solve that. When I test it successfully, I will update the EFI.

**Comment by arifzeeshan** [comment]
How did you added support for HEVC decoding ? I just realized that it's broken for mine too.

**Comment by Lovely-XPP** [comment]
You can try to delete the key "AAPL,slot-name" in your DeciceProperies of Graphic card like this in your config:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66028151/130411035-e75f81d8-1795-4eaa-9669-22cf920ca00d.png">

**Comment by arifzeeshan** [comment]
That doesn't fix it.

**Comment by Lovely-XPP** [comment]
I can't remember what I did, because  I am working on the sleep problems with the EFI changing rapidly. So,  I upload the present EFI to you here. It works for me about the HEVC decoding, you can have a try.


[EFI.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7030216/EFI.zip)

**Comment by arifzeeshan** [comment]
Okay, I fixed it by removing the whole PCI (0x0, 0x02) slot as Whatevergreen.kext automatically injects all the properties.

**Comment by Lovely-XPP** [comment]
I have a solution on sleep issue, but it conflicts with the key "fn + insert" and LID sleep. According to tests these days, I find the problem is S3 sleep mode. Therefore, I use SSDT to ban it, but it comes that the key "fn + insert" and LID sleep can not work. Then I use another way to sleep called [AOAC](https://github.com/5T33Z0/OC-Little-Translated/tree/main/04.%20Fixing%20Sleep%20and%20Wake%20Issues/Fixing%20AOAC%20Machines/iiii%20AOAC%20wake-up%20method). I will upload EFI later.

**Comment by Lovely-XPP** [comment]
I have a solution on sleep issue, but it conflicts with the key "fn + insert" and LID sleep. According to tests these days, I find the problem is S3 sleep mode. Therefore, I use SSDT to ban it, but it comes that the key "fn + insert" and LID sleep can not work. Then I use another way to sleep called [AOAC](https://github.com/5T33Z0/OC-Little-Translated/tree/main/04.%20Fixing%20Sleep%20and%20Wake%20Issues/Fixing%20AOAC%20Machines/iiii%20AOAC%20wake-up%20method). I will upload EFI later.

**Comment by arifzeeshan** [comment]
So, did you fixed the deepidle ?

**Comment by arifzeeshan** [comment]
AFAIK, your System needs to support DeepIdle or AOAC(Always on Always connected) specification for it to work.

**Comment by Lovely-XPP** [comment]
It is not necessary for you to have  DeepIdle or AOAC support. For me, I edit the SSDT-PCI0.LPCB-Wake-AOAC.dsl and it works for me. It supports key "Fn + insert" to sleep, but Lid device do not support sleep, I am working on it. I want to edit the SSDTs to support Lid device with Deepldle.

**Comment by Lovely-XPP** [comment]
For your doubt, the method also suit the Laptop without AOAC and I have tested it successfully. 

<img width="919" alt="image" src="https://user-images.githubusercontent.com/66028151/130468369-89ecfc23-070a-4cec-9b4b-6790203dec7c.png">

**Comment by arifzeeshan** [comment]
When in Fn+Insert sleep, breathing light is working for you ?

**Comment by Lovely-XPP** [comment]
No, actually when you sleep by click the sleep button in the apple menu(apple logo), breathing light don not work. It is normal for that. Here is the reason:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/66028151/130479532-14c69e91-4e46-4b75-9690-df1a43daaddf.png">

**Comment by arifzeeshan** [comment]
For me, without the SSDT-DeepIdle, breathing light works. But Sleep gets broken with SSDT-DeepIdle, so can't test Breathing light.

**Comment by Lovely-XPP** [comment]
If you sleep worked well before, you can use your config before. For me, previous config will cause black screen after sleep  and I had to reboot. But when I use SSDT-Deepldle, sleep well except breathing light. If you want to use this method, you may also add these SSDTs:

* SSDT-NameS3-disable
* SSDT-DeepIdle
* SSDT-PCI0.LPCB-Wake-AOAC

and rename _S3 to XS3 by add patch:

``
Find: 5F53335F
Replace:5853335F
Comment:_S3 to XS3
``

This method can only wake up by Power button.

**Comment by arifzeeshan** [comment]
I used the same SSDTs and ACPI renames but Sleep is broken. I wonder how much difference between DeepIdle and normal S3 sleep.

**Comment by Lovely-XPP** [comment]
I will do a test about the consumption of power in DeepIdle sleep. But for S3 sleep, my laptop can't work on it. So I can't get the data from S3 sleep.

**Comment by arifzeeshan** [comment]
Can you update the repo with what changes did you make to make SleepIdle work in the SSDT. I'll try once more with your insights.

**Comment by Lovely-XPP** [comment]
Will the new EFI works in your laptop? Here is my test result with DeepIdle:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/66028151/130538454-9328b6fe-7516-4cc6-a827-d4fcf9b840fc.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/66028151/130538509-04755335-d28d-4911-90c5-8ac64772b76f.png">

My battery health is about 73% and my laptop consumes about 4% power per hour in DeepIdle sleep.

**Comment by arifzeeshan** [comment]
No, the latest EFI doesn't work for me. Something is wrong, it power drain is too much. Mine just consumes 2-3% in 8 hrs S3 sleep. Btw, what is that app you are using to show battery percentage ?

**Comment by Lovely-XPP** [comment]
Ok, thank for your feedback, I may desperate into 2 branches for S3 sleep mode and DeepIdle mode. The app is called `Sensei`. If you want this app, you can leave your email so that I can send it to you.

**Comment by arifzeeshan** [comment]
Either your Battery is at fault or you need to investigate in what is consuming so much power. You can use [Power metrics](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheTaskLevel.html#//apple_ref/doc/uid/TP40013929-CH35-SW10) **powermetrics** is a Mac-only command-line utility that provides many high-quality power-related measurements. It is most useful for getting CPU, GPU and wakeup measurements in a precise and easily scriptable fashion.

**Comment by Lovely-XPP** [comment]
Ok, I will have a try, thank you.

**Comment by Lovely-XPP** [comment]
Unbelievably, I just fix up S3 sleep mode by adding SSDT-GPRW and patch `GPRW to XPRW`. I will test S3 sleep later and update EFI.

**Comment by Lovely-XPP** [comment]
My S3 sleep also works well. It consumes about 3% power in 8 hour.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/66028151/130710193-d630999e-b18a-48af-9b80-b637eacdc7bd.png">

Thanks for your suggestions and feedback.

**Comment by arifzeeshan** [comment]
Could you please search on your OEM DSDT the following.
- Open MaciASL
- Click on "File > New From ACPI" and select `FACP.aml`
- Search for `Low Power S0 Idle`. Tell me if it is = `1` or `0`


<img width="844" alt="Screenshot 2021-08-25 at 12 56 42 PM" src="https://user-images.githubusercontent.com/26674272/130745618-1dfb7356-2277-4bc1-aad7-b76a52edeab1.png">

**Comment by Lovely-XPP** [comment]
It is`0`.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/66028151/130751700-f1edee45-311a-4f80-8062-333d4b442dce.png">
