### ISSUE TITLE
E7480 - Can't boot BigSur (1080p display variant) 

### ISSUE THREAD

**Issue by vijayaragavan2506** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#12]
Hi.. Thanks for updated guide for E7480.. I have tried to boot BigSur 11.6.2 with your EFI.. I have same config as yours.. But Full HD display.. I'm getting errors..![20211226_142432.jpg](https://user-images.githubusercontent.com/72325834/147403443-f01e203d-e715-451d-aa44-bb6c80258745.jpg)

**Comment by NontTheKiller** [comment]
What error? Can you take a screenshot of the error?

**Comment by vijayaragavan2506** [comment]
> What error? Can you take a screenshot of the error?

Every time it stucks at same (All kernel threads created fpr interface lo0 have been scheduled at least once. Proceeding) ![20211226_143040.jpg](https://user-images.githubusercontent.com/72325834/147403561-a8047a2c-2f59-429f-944d-b9b6a6fe750c.jpg)

**Comment by Lovely-XPP** [comment]
Maybe it has some problems with the kext ``VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext ``, I have disabled it in the config files as I attach below. Maybe you can have a try.
[config.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7776773/config.zip)

**Comment by vijayaragavan2506** [comment]
Sure.. I will try to boot without any voodoo kexts...

**Comment by Lovely-XPP** [comment]
Maybe you can try the previous release version, which had old version Voodoo kexts.

**Comment by Lovely-XPP** [comment]
Maybe you can try the latest Voodoo kext, which fixed kernel panics.
https://github.com/dortania/build-repo/releases/download/VoodooPS2-2f7dac2/VoodooPS2Controller-2.2.9-RELEASE.zip
