### ISSUE TITLE
trackpad not working properly

### ISSUE THREAD

**Issue by gaslarfa** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#18]
Greetings I have a small problem with the trackpad.

The drawback is that every time I'm going to use it, it's as if I'm using both fingers at the same time instead of just one.

I thought my trackpad was defective but on windows it works perfectly.

Could you tell me why this happens?

I am using MacOss Monterrey in version 12.5.1 with opencore 8.3

**Comment by Lovely-XPP** [comment]
Maybe you can try this one, but you need to complie by yourself.😂(I will build it later.) 
https://github.com/SkyrilHD/AlpsHID/tree/proj-+-pressure-test
```bash
git clone -b proj-+-pressure-test https://github.com/SkyrilHD/AlpsHID.git
cd AlpsHID
git clone https://github.com/acidanthera/MacKernelSDK.git
```
Open the main project in Xcode and build away and replace the kext `AlpsHID.kext`. : )
If the issue exists, you can try other branches.

**Comment by Lovely-XPP** [comment]
I am sorry that I have no spare space for installing Xcode, so I can't build it for you😔. If possible, you can build by yourself.

**Comment by H3xidecimal** [comment]
I can confirm this worked for me. I pulled down the repo and compiled the new AlpsHID.kext file and it corrected the strange trackpad behavior.

**Comment by H3xidecimal** [comment]
[AlpsHID.kext.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/10076397/AlpsHID.kext.zip)

There you go. No problem, happy to help!

**Comment by Lovely-XPP** [comment]
Thanks a lot :)
