### ISSUE TITLE
Stuck in theusing 16384 buffer headers and 10240 cluster 

### ISSUE THREAD

**Issue by Way2LOose4** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#19]
hi , sorry to bother you
when i try to set Montery and Ven , i find there is a missing ssdt-als0(which leads me stuck in first time)
and  i stuck in theusing 16384 buffer headers and 10240 cluster 
i don't konw what happen, some one said it maybe have connection with video card and wireless internet card ( i use bcm94360z3)
sorry again

**Comment by Way2LOose4** [comment]
https://img1.imgtp.com/2022/09/11/XCMzbSQB.jpg
Here is the picture of the issues

**Comment by Lovely-XPP** [comment]
I am sorry that I have no idea, but did you try add ssdt-als0 to your OC folder?

**Comment by Lovely-XPP** [comment]
By the way, your main problem is `no nvram varlable` and I will try searching for solution later.

**Comment by Lovely-XPP** [comment]
Did you follow the `Recommended Bios Setup` in ReadME, and you can also try these method as below, maybe it works: 
1. reset nvram
2. disable the entry `USBMap.kext` in `Kernel` of the config.plist.
3. enable the entry `NVMeFix.kext` in `Kernel` of the config.plist.

**Comment by Way2LOose4** [comment]
As you see, I add the ssdt-als0 to my oc.
But, it still stuck after try the method.
I reset my bios setting and  nvram but the issue still happened.

**Comment by Way2LOose4** [comment]
by the way, my bios version is 1.26.0,
if you need, here is my system information
wifi card be moved by myself for edit issue
https://img1.imgtp.com/2022/09/12/a0k0OgDY.jpg
https://img1.imgtp.com/2022/09/12/DpyP52Cl.jpg

**Comment by Lovely-XPP** [comment]
Maybe you can get some ideas from here: https://www.tonymacx86.com/threads/solved-amfiloadtrustedkeysfromnvram-failed-getting-nvram-using-16384-buffer.298735/.

In my opinion, maybe something wrong with ACPI Patch.

**Comment by Lovely-XPP** [comment]
As the solution on the website attached says, you can try to add ACPI Patch like this one in OpenCore configurator:

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/66028151/190047798-245d06b0-4935-4ddc-bad5-fe6975b4344a.png">

**Comment by Lovely-XPP** [comment]
By the way, your hardware and bios version is as same as mine (except wifi card, but it is not important), so it's strange to meet panic. 😑

**Comment by Way2LOose4** [comment]
[EFI.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/9592953/EFI.zip)
Sorry for so late response, I buy a new in Taobao, u can see if it working.
