### ISSUE TITLE
External Microphone

### ISSUE THREAD

**Issue by aancw** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#2]
Hi,
This repo is awesome, thank you for making it. I'm trying to use external microphone and plug it in jack but it's not detected. Have you try external microphone or headphone microphone? I'm so confused because I can't use mic for my webinar.

Thank you.

**Comment by aancw** [comment]
I'm tested it with text edit. When pressing home it doesn't go to beginning of paragraph instead it scroll to the top of file. It's like page up.

I will try to reset nvram

**Comment by Lovely-XPP** [comment]
I get some information about the AppleALC and tried to customize my own config of ALC256 these days. However, it doesn't work. In fact, origin layout-id 21 suit our device as well. Maybe it is a bug or something I do not notice. I am not specializing in sound-card, so I decide to give up and wait for kext update.

**Comment by aancw** [comment]
If it's a bug, we need to submit PR to AppleLC kext? So he notice this issue too.

**Comment by Lovely-XPP** [comment]
Yes, I will. I will try once more. If not success, I will submit this issue to AppleALC. I will do it in my free time.

**Comment by aancw** [comment]
Hi, do you use external mouse or trackpad/mousepad? I'm using mousepad and it not working. Do you have the same issue too?

**Comment by Lovely-XPP** [comment]
I use external mouse, it works well. Maybe you can try to customize your USB port by this tool: [USBMap](https://github.com/corpnewt/USBMap).

**Comment by aancw** [comment]
My external mouse is working well. What not working is my internal touchpad.

**Comment by Lovely-XPP** [comment]
I don't have this issue. Do you use the latest EFI ? Maybe it is the SDST's problem.

**Comment by ShevonKuan** [comment]
小鹏鹏最叻

**Comment by aancw** [comment]
I'm using the latest. Wait i will try to download your efi and reset nvram.

**Comment by Lovely-XPP** [comment]
It is the problem of the kexts of wireless card. I will publish EFI for Intel wireless card later.

**Comment by aancw** [comment]
Wireless card? It said vodooinput. I'm using airportlwm

**Comment by Lovely-XPP** [comment]
Oh, maybe I know the issue. You can check if the `VoodooI2C.kext/Contents/PlugIns/VoodooInput.kext` disabled. If not, you may disable it.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66028151/132192733-b9f73953-61b2-48c8-af92-baa65a36c9f8.png">

**Comment by aancw** [comment]
Wait, let me check bro

**Comment by aancw** [comment]
The error and kernel panic is dissapear. But it still stuck at this 

![IMG_20210906_171131.jpg](https://user-images.githubusercontent.com/6284204/132201186-8223dc18-c9c9-44c7-a490-723e37702703.jpg)

**Comment by Lovely-XPP** [comment]
I am sorry that I don not know the exactly issue about the figure. But, I have updated EFI just now included  a config of intel  wireless card supported. You can have a try. I believe it may help you, for our devices is actually the same except the wifi card.

**Comment by Lovely-XPP** [comment]
Download link: [Click here](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/releases/tag/0.7.2.4)

and don't forget to read the instruction as below:

This version has add Intel wireless card support ,update kexts and partly support hot-plug for type-c or thunderbolt.

For Intel-wireless-card user, you need to

* Delete the existing `config.plist`
* Change the name of `config-intel-wireless-card.plist` into `config.plist`

Information about hot-plug for type-c or thunderbolt:

* You still need to plug in the device of thunderbolt(or type-C) before you turn on your computer, but after that you can hot-plug in your system.
* Wake up from sleep, the thunderbolt(or type - C) can not work, even if plug again. 

More detail in [here](https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/).

**Comment by aancw** [comment]
I will try using your latest efi. Is my issue related to AppleSMC? 

Hey, do you have telegram account? Maybe we can discuss about the efi more real time.

**Comment by aancw** [comment]
If I'm using my EFI and merge your efi, it works. But if only using your EFI, it stuck.

**Comment by aancw** [comment]
Using your uptodate EFI. It still stuck at AppleSMC

**Comment by aancw** [comment]
Detail report from apple report tool

![IMG_20210907_004407.jpg](https://user-images.githubusercontent.com/6284204/132249999-62980553-1e63-47bc-a02c-c8c7629791ca.jpg)

**Comment by aancw** [comment]
Comparing Flashdrive EFI with SSD EFI the different that I suspect is only config.plist
![image](https://user-images.githubusercontent.com/6284204/132253304-7864aa82-b466-4866-add4-78d48a8b3a98.png)

**Comment by Lovely-XPP** [comment]
OK, my phone number is +8613798633495

> I will try using your latest efi. Is my issue related to AppleSMC?
> 
> Hey, do you have telegram account? Maybe we can discuss about the efi more real time.

**Comment by Lovely-XPP** [comment]
I check out the config, I found I inject my BCM card information in device properties, so I check again and delete useless device properties. I have updated it. Maybe you can try again.😂

**Comment by aancw** [comment]
It work with combojack and macos version 11.6.
