### ISSUE TITLE
AlpsHID.kext not working properly - solution

### ISSUE THREAD

**Issue by RJJvW** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#21]
With the AlpsHID.kext v1.3 the trackpad is not working properly on my E7480.
I went over to https://github.com/blankmac/AlpsHID and downloaded AlpsHID.kext v1.2.
I replaced the original in the EFI folder with v1.2 and now the trackpad is working properly.
Ik only replaced AlpsHID.kext but not VoodooI2CHID.kext. Also I did not change anything in config.plist.

**Comment by Lovely-XPP** [comment]
Maybe the old version works better. I will replace it. Thanks you a lot. : )
