### ISSUE TITLE
Stopping the installation (solved) and Black screen after waking up from sleep(solved)

### ISSUE THREAD

**Issue by krzysinek** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#22]
Hello, 

Firstly, congratulation for great job to creating this EFI !!!

I use the EFI on Dell E7480 with non touch display 1080p (Ventura 13.0.1).
I had a problem installing Ventura with this EFI (look at screen below) but I fix it by set ReleaseUsbOwnership=true in config.plist.

![FEDCBD5B-5AE9-49F3-BF10-00C3C3564E53_1_105_c](https://user-images.githubusercontent.com/119707589/205399474-f155cb8c-a12a-4d1c-b10c-3a12b2302094.jpeg)

Now, I have problem with sleep. After sleep and press power button or Fn+Insert I have black screen.
In hackintool internal display is visible as Unknown Display. In IORegistryControler I have only AppleBacklightDisplay (not AppleDisplay).
I Have original dell dock station with USB-C cable and the problem with sleep is absent with dock station and external monitor.

I Try set EDID, modify the PciRoot(0x0)/Pci(0x2,0x0) but without success.
I've used the latest release EFI (OC 0.8.6 with correct AlpsHID which repair trackpad :-) ).  
Have you got any idea what I can do to repair the sleep?

Best regards

**Comment by Lovely-XPP** [comment]
Thanks for your feedback.

For sleep issue, firstly you can use hackintool.app to check and fix your setting of sleep.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/66028151/205424853-fe635099-f929-46b8-bfac-3e26aded7b44.png">

Secondly, turn off App snap in system setting.

These setting maybe works.

For me, I studied sleep issue for a long period of time before, and check lots of information. For 7480, I learn that the main problem is SSDT, so I take a long time on it and finally works fine on my 7480.

Btw, sleep issue is normal in hackintosh, and I think the latest config is the best solution for now.

**Comment by krzysinek** [comment]
@Lovely-XPP  I would like to know what kexts you have in the /Library/Extension/ ?

**Comment by Lovely-XPP** [comment]
I am sorry that I don't have my E7480 here, so I can't help you. :(

**Comment by krzysinek** [comment]
No problem. Thanks for information.
I found that if the usb-c cable is connected, sleep works.

**Comment by krzysinek** [comment]
In Ventura I uncheck in opencore configurator in UEFI -> Drivers -> TbTPowerForce.efi and sleep is working. I have to check another functions (e.g. usb-c).

**Comment by Lovely-XPP** [comment]
Thanks for your feedback, I think if you uncheck this driver, you can't hot-plug your thunderbolt devices after boot. So if you have no need on it, just uncheck. Theoretically, it have not impact on USB-C.

**Comment by krzysinek** [comment]
I read about this TbTPowerForce.efi (Dortania - Fixing Thunderbolt) and I am surprised (probably you too). When I had it checked, sleep and hot-plug didn't work in Ventura. Currently (when I had it unchecked) hot-plug works and wake up from sleep works :-)
My problem ( After sleep and press power button or Fn+Insert I have black screen) 
is SOLVED.

Below I attach screenshot from current Driver configuration.
![image](https://user-images.githubusercontent.com/119707589/206856629-0807da9e-b07d-4f3f-af40-18f272c50099.png)

Best regards

**Comment by krzysinek** [comment]
Resolved.

**Comment by Lovely-XPP** [comment]
Thanks for your feedbacks, I will update the config : ).
