### ISSUE TITLE
Headphone Jack

### ISSUE THREAD

**Issue by NontTheKiller** [Lovely-XPP/Dell-Latitude-E7480-Hackintosh#5]
I heard that you have some headphone jack microphone problem. I not sure that method that I give will work on your device but it work on my latitude 7480

1. Try [Combo Jack](https://github.com/hackintosh-stuff/ComboJack) This Method work on my device.
2. if first method not work try SSDT I attach below (It from [latitude 7480 clover](https://github.com/TranNgocKhoa/Dell-Latitude-7480-Hackintosh)) and install codec commander

Let me know that this method work on your device or not
Oh this is my latitude 7480 spec

- Dell Latitude E7480
- Intel core i5-7200u
- Intel HD Graphics 620
- 16gb of ram 
- SandDisk X400 M.2 2280 512GB (From Factory)
- Intel Wireless AC 8265

[SSDT-ALC256.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7134776/SSDT-ALC256.zip)

**Comment by Lovely-XPP** [comment]
Thanks for your suggestions! However, It does't work on my device. Do you use AppleALC with Combo Jack with OC?

**Comment by NontTheKiller** [comment]
Yes, Try layout 21 with the combo jack. I have a problem with the new version of combo jack. I have some backup of the old version. i will give you a old version try it. 
[ComboJack-master.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7150954/ComboJack-master.zip)
(You have to run the install.sh that I give in a old version if it not install you can give a picture in the terminal I will take a look and don't forget to install verbstub.kext in the OC and snapshot it) 😊

**Comment by aancw** [comment]
I've used combojack with layout-id 21 it doesn't work.

**Comment by NontTheKiller** [comment]
Try selecting another type of mic. mine was the line in headphone but I select line in it doesn't work I try select headphone it work I don't know why try select another type of it

**Comment by Lovely-XPP** [comment]
I have update repo to OC 0.7.3 and I will publish a stable release after solving some issues.

**Comment by aancw** [comment]
I've selected the headphone and it still doesn't work before you create PR. Maybe ssdt problem.

**Comment by NontTheKiller** [comment]
Can you try remove ssdt-256.aml and the codec commander, and try again

**Comment by aancw** [comment]
I will wait @Lovely-XPP update the working version.

**Comment by aancw** [comment]
> Try selecting another type of mic. mine was the line in but I select line in it doesn't work I try select headphone it work I don't know why try select another type of it

Can you post screenshot for audio setting? What external mic/headphone detected?

**Comment by NontTheKiller** [comment]
@aancw I cant right now I'm not in macOS. I will install macOS Catalina in Saturday. I will take a picture in Saturday.

**Comment by aancw** [comment]
@NontTheKiller Big Sur or Monterey

**Comment by NontTheKiller** [comment]
@aancw Never try in Big Sur or Monterey. I have try in clover with Catalina and install codec commander to s/l/e and everything work all the audio. But when I move to Opencore I didn't use codec commander i use combo jack version that i have in the comment.

**Comment by aancw** [comment]
So, combojack is worked with opencore? Me and @Lovely-XPP has discussed that it worked on previous macos release. But in bigsur/monterey it still doesn't work. But will try to use the ssdt from repo you mentioned.

**Comment by NontTheKiller** [comment]
@aancw I don’t know why you guy not working if when you install in terminal and have this error in the picture try version that I give. I have try in Big Sur and it work too

![](https://user-images.githubusercontent.com/49932650/126613746-70b2622c-153f-4dc2-a244-d9cc82f1bf69.png)

**Comment by aancw** [comment]
The combojack is successfully installed and worked but the audio is still using internal audio not mic from headphone or external headphone. Can you post ss for audio setting?

**Comment by NontTheKiller** [comment]
@aancw do you have some pop up things when you plug the headphone?

**Comment by aancw** [comment]
Yes it's. It show popup. But whatever i choose, the audio setting is still not detected my mic.

**Comment by aancw** [comment]
Please post your audio output setting

**Comment by NontTheKiller** [comment]
> Please post your audio output setting

I said I can't right now because I'm not in macOS I will sent you a screenshot in Saturday.

**Comment by aancw** [comment]
Uploading Screen Recording 2021-09-13 at 20.44.23.mov…

**Comment by aancw** [comment]
Here is my combojack @NontTheKiller  https://imgur.com/a/7dNmpX0

**Comment by NontTheKiller** [comment]
@aancw try all option? Have the same problem?

**Comment by NontTheKiller** [comment]
@aancw can you try another headphone?

**Comment by aancw** [comment]
Yes, i'm using headphone, external mic it doesnt work

**Comment by aancw** [comment]
which one the input from combojack? only internal and line. 

![image](https://user-images.githubusercontent.com/6284204/133099524-e33e70b5-9eb2-4527-bf25-ca802ba2d050.png)

**Comment by NontTheKiller** [comment]
it a line in

**Comment by NontTheKiller** [comment]
@aancw do you have another headphone to test? If you have another can you test for me?

**Comment by aancw** [comment]
I already did, told you many time and it doesnt work.

**Comment by NontTheKiller** [comment]
> I already did, told you many time and it doesnt work.

Oh ok can you dump a IOresgisty log pls I will take a look

**Comment by aancw** [comment]
I will try add ssdt-alc.aml first.

**Comment by NontTheKiller** [comment]
> I will try add ssdt-alc.aml first.

Ok don’t forget to add codec commander

**Comment by aancw** [comment]
It's the right way to do?
![image](https://user-images.githubusercontent.com/6284204/133101403-7e82dc7e-88dc-4d87-8b19-1dda8b38f90e.png)


I've remove the codec commander when installing combojack. Where can I download and what's step by step?

**Comment by NontTheKiller** [comment]
> It's the right way to do?
> ![image](https://user-images.githubusercontent.com/6284204/133101403-7e82dc7e-88dc-4d87-8b19-1dda8b38f90e.png)
> 
> I've remove the codec commander and ALCPlugFix when installing combojack. Where can I download and what's step by step?

Wait did you install verbstub.kext in oc

**Comment by NontTheKiller** [comment]
You can download [codec commander](https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/) here. insert after applealc (I have seen some problem when you boot codec commander in Opencore with macOS Big Sur and Monterey it cause kernel panic try put it on flash drive first)

**Comment by aancw** [comment]
Yes i'm install the verbstub. I've added ssdt-alc.aml and still doesnt work.

Check my verbstub position

![image](https://user-images.githubusercontent.com/6284204/133104181-850c2e08-f2a7-4809-ab21-6257d19d047a.png)

**Comment by NontTheKiller** [comment]
I think the loading position is important try put verbstub after applealc and remove ssdt 
Only use SSDT with codec commander

**Comment by aancw** [comment]
![image](https://user-images.githubusercontent.com/6284204/133104939-d8f224ed-b72e-470f-8d14-66b6a8a84d1f.png)

**Comment by aancw** [comment]
okay i will remove the ssdt and reposition. will reboot.

**Comment by aancw** [comment]
Still doesn't work with reposition

**Comment by Lovely-XPP** [comment]
I am sorry that both of your methods can not solve the issue, but still thanks for your suggestion.

**Comment by NontTheKiller** [comment]
@aancw @Lovely-XPP can you guy dump ioregistry. I want to see that combo jack is load or not because I see @aancw video and the sound input didn't change to headphone.

**Comment by aancw** [comment]
Wait, let me dump it. Yes from my video, the audio input is not changed and only internal mic is working

**Comment by NontTheKiller** [comment]
> Wait, let me dump it. Yes from my video, the audio input is not changed and only internal mic is working

I think that combo jack not fully load. I want you guys to dump ioregistry logs and i will take a look

**Comment by aancw** [comment]
I will let @Lovely-XPP dump the ioregistry. Because i don't know how to do it.

**Comment by NontTheKiller** [comment]
> I will let @Lovely-XPP dump the ioregistry. Because i don't know how to do it.

open ioregistry and click on file and save as

**Comment by Lovely-XPP** [comment]
Is this one?

[MacBook Pro.ioreg.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7159969/MacBook.Pro.ioreg.zip)

**Comment by NontTheKiller** [comment]
> Is this one?
> 
> [MacBook Pro.ioreg.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7159969/MacBook.Pro.ioreg.zip)

it said file is corruped try dump it again or you can use runme.app from olarila.com

**Comment by Lovely-XPP** [comment]
Ok, check this please. BTW, do I need to install ComboJack first?

[Ioreg.txt](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7160323/Ioreg.txt)

**Comment by NontTheKiller** [comment]
> Ok, check this please. BTW, do I need to install ComboJack first?
> 
> [Ioreg.txt](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7160323/Ioreg.txt)

yes

**Comment by Lovely-XPP** [comment]
Ok, wait a minute please.

**Comment by NontTheKiller** [comment]
> Ok, wait a minute please.

can you dump with the app i give because it will get all information about the system 
https://www.olarila.com/topic/10301-olarila-runme-dumper-app/

**Comment by aancw** [comment]
I'm running this tools, but why the tool say: removing resources dir

**Comment by NontTheKiller** [comment]
> I'm running this tools, but why the tool say: removing resources dir

can you take a picture of it?

**Comment by aancw** [comment]
This tools say:
```
IOREG dump failed. Retrying by increasing delays...
Increased delay by x2 times. Retrying...
IOREG dump failed. Retrying by increasing delays...
Increased delay by x3 times. Retrying...
IOREG dump failed. Retrying by increasing delays...
IOREG dump has failed 3 times. Dumping generic IOREG report instead.
```

[Ioreg.txt](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7160439/Ioreg.txt)

**Comment by aancw** [comment]
![image](https://user-images.githubusercontent.com/6284204/133229125-c13ef4ed-f5c7-4dac-96a9-c5b3b5d40d19.png)

**Comment by NontTheKiller** [comment]
@aancw it should be a settings pop up about accessibility and you have to check for it

**Comment by Lovely-XPP** [comment]
The whole zip is as below.

[Infomation.zip](https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/files/7160610/Infomation.zip)

**Comment by aancw** [comment]
> @aancw it should be a settings pop up about accessibility and you have to check for it

Already did and still the same. I thing information from @Lovely-XPP is same as mine.

**Comment by NontTheKiller** [comment]
@Lovely-XPP can you plug your headphone and sent Ioregistry log again pls

**Comment by Lovely-XPP** [comment]
I don't have headphone now😂, I will try it tonight.

**Comment by Lovely-XPP** [comment]
It's Ok. I find it work in Big Sur 11.6 with the choice of "headphone mic". Thanks.

**Comment by NontTheKiller** [comment]
@Lovely-XPP FIX
 @aancw how about you can you run rumme.app by Olarila again pls I want to see Ioregistry

**Comment by NontTheKiller** [comment]
@Lovely-XPP what combo jack version are you using? Because when I use combo jack from GitHub I get a error when it install.

**Comment by aancw** [comment]
Confirmed it works with headset options.

**Comment by Lovely-XPP** [comment]
> @Lovely-XPP what combo jack version are you using? Because when I use combo jack from GitHub I get a error when it install.

I use the latest version of ComboJack in its repo with macOS 11.6.

**Comment by NontTheKiller** [comment]
> > @Lovely-XPP what combo jack version are you using? Because when I use combo jack from GitHub I get a error when it install.
> 
> I use the latest version of ComboJack in its repo with macOS 11.6.

Ok I will try. Thank for you guys help
